CREATE TABLE PERSONA(
DPI NUMBER(15) NOT NULL,
PNOMBRE VARCHAR2(50) NOT NULL,
SNOMBRE VARCHAR2(50),
PAPELLIDO VARCHAR2(50) NOT NULL,
SAPELLIDO VARCHAR2(50) NOT NULL,
DIRECCION NVARCHAR2(50) NOT NULL,
FECHA_NAC DATE NOT NULL,
COD_CIUDAD NUMBER(10) NOT NULL,
CONSTRAINT PK_DPI PRIMARY KEY(DPI)
);

CREATE TABLE TELEFONO(
EMPRESA VARCHAR2(50),
NUMERO NUMBER(8),
DPI NUMBER(15) NOT NULL,
CONSTRAINT FK_TELEFONO_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI)
);

CREATE TABLE CIUDAD(
COD_CIUDAD NUMBER(10) NOT NULL,
MUNICIPIO VARCHAR2(50) NOT NULL,
DEPARTAMENTO VARCHAR2(50) NOT NULL,
PAIS VARCHAR2(50) NOT NULL,
CONSTRAINT PK_COD_CIUDAD PRIMARY KEY(COD_CIUDAD)
);

CREATE TABLE CLIENTE(
COD_CLIENTE NUMBER(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
DPI NUMBER(15) NOT NULL,
CONSTRAINT PK_COD_CLIENTE PRIMARY KEY(COD_CLIENTE),
CONSTRAINT FK_CLIENTE_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI)
);


CREATE TABLE EMPLEADO(
NIT NUMBER(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
HORAS_TRABAJO NUMBER(2) NOT NULL,
DPI NUMBER(15) NOT NULL,
COD_CARGO NUMBER(10) NOT NULL,
CONSTRAINT PK_NIT PRIMARY KEY(NIT),
CONSTRAINT FK_EMPLEADO_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI)
);

CREATE TABLE CARGO(
COD_CARGO NUMBER(10) NOT NULL,
CARGO VARCHAR2(50) NOT NULL,
AREA VARCHAR2(50) NOT NULL,
SUELDO NUMBER(10) NOT NULL,
CONSTRAINT PK_COD_CARGO PRIMARY KEY(COD_CARGO)
);


CREATE TABLE CUENTA(
COD_CUENTA NUMBER(15) NOT NULL,
TIPO_CUENTA VARCHAR2(20) NOT NULL,
TIPO_MONEDA VARCHAR2(20) NOT NULL,
DPI NUMBER(15) NOT NULL,
CONSTRAINT PK_COD_CUENTA PRIMARY KEY(COD_CUENTA),
CONSTRAINT FK_CUENTA_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI)
);

CREATE TABLE FONDOS(
COD_CUENTA NUMBER(15)NOT NULL,
SALDO_CONTABLE NUMBER(10) NOT NULL,
SALDO_BLOQUEADO NUMBER(10) NOT NULL,
SALDO_DISPONIBLE NUMBER(10) NOT NULL,
SALDO_ANTERIOR NUMBER(10) NOT NULL,
CONSTRAINT FK_FONDOS_COD_CUENTA FOREIGN KEY(COD_CUENTA) REFERENCES CUENTA(COD_CUENTA)
);

CREATE TABLE CREDITOS(
COD_CREDITO NUMBER(10) NOT NULL,
MONTO_CONCEDIDO NUMBER(10) NOT NULL,
MONTO_UTILIZADO NUMBER(10),
MONTO_DISPONIBLE NUMBER(10),
INTERES NUMBER(10),
PLAZO NUMBER(10),
MONEDA VARCHAR2(50),
FECHA_APROBACION DATE,
FECHA_VENCIMIENTO DATE,
DPI NUMBER(15) NOT NULL,
COD_FIADOR NUMBER(10) NOT NULL,
CONSTRAINT PK_COD_CREDITO PRIMARY KEY(COD_CREDITO),
CONSTRAINT FK_CREDITOS_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI),
CONSTRAINT FK_CREDITOS_COD_FIADOR FOREIGN KEY(COD_FIADOR) REFERENCES FIADOR(COD_FIADOR)
);

CREATE TABLE FIADOR(
COD_FIADOR NUMBER(10) NOT NULL,
OCUPACION VARCHAR2(50),
INSTITUCION VARCHAR2(50),
SALARIO NUMBER(10),
DPI NUMBER(15),
CONSTRAINT PK_COD_FIADOR PRIMARY KEY(COD_FIADOR),
CONSTRAINT FK_FIADOR_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI)
);


CREATE TABLE TRANSACCIONES
(
COD_TRANSACCION NUMBER(15) NOT NULL,
COD_USUARIO NUMBER(10) NOT NULL,
FECHA DATE NOT NULL
);

CREATE TABLE DEPOSITOS(
COD_DEPOSITO NUMBER(10) NOT NULL,
COD_CUENTA NUMBER(15) NOT NULL,
DPI NUMBER(15) NOT NULL,
MONTO NUMBER(10) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_COD_DEPOSITO PRIMARY KEY(COD_DEPOSITO),
CONSTRAINT FK_DEPOSITOS_COD_CUENTA FOREIGN KEY(COD_CUENTA) REFERENCES CUENTA(COD_CUENTA)
);

CREATE TABLE RETIROS(
COD_RETIRO NUMBER(10) NOT NULL,
COD_CUENTA   NUMBER(15) NOT NULL,
COD_CHEQUE NUMBER(10) NOT NULL,
FECHA_CHEQUE NUMBER(10) NOT NULL,
FECHA DATE NOT NULL,
DPI NUMBER(10) NOT NULL,
MONTO NUMBER(10) NOT NULL,
COD_TARJETA NUMBER(10) NULL,
CONSTRAINT PK_COD_RETIRO PRIMARY KEY(COD_RETIRO),
CONSTRAINT FK_RETIROS FOREIGN KEY(COD_CUENTA) REFERENCES CUENTA(COD_CUENTA),
CONSTRAINT FK_RETIROS FOREIGN KEY(COD_CHEQUE) REFERENCES CHEQUE(COD_CHEQUE)
);

CREATE TABLE SUCURSAL(
COD_SUCURSAL NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DIRECCION NVARCHAR2(50) NOT NULL,
COD_CIUDAD NUMBER(10) NOT NULL,
CONSTRAINT PK_COD_SUCURSAL PRIMARY KEY(COD_SUCURSAL),
CONSTRAINT FK_SUCURSAL_COD_CIUDAD FOREIGN KEY(COD_CIUDAD) REFERENCES CIUDAD(COD_CIUDAD)
);

CREATE TABLE USUARIOS(
COD_USUARIO NUMBER(10) NOT NULL,
USUARIO VARCHAR2(50) NOT NULL,
CONTRASEÑA NVARCHAR2(50) NOT NULL,
COD_CLIENTE NUMBER(15) NOT NULL,
CONSTRAINT PK_COD_USUARIO PRIMARY KEY(COD_USUARIO),
CONSTRAINT FK_USUARIOS_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES PERSONA(DPI)
);

CREATE TABLE USUARIOS_FORMALES(
NIT NUMBER(10) NOT NULL,
USUARIO VARCHAR2(50) NOT NULL,
CONTRASEÑA NVARCHAR2(50) NOT NULL,
CONSTRAINT FK_USU_FORM_NIT FOREIGN KEY(NIT) REFERENCES EMPLEADO(NIT)
);

CREATE TABLE PROFESION(
COD_PROFESION NUMBER(10) NOT NULL,
TITULO VARCHAR2(50) NOT NULL,
DIPLOMA VARCHAR2(50) NULL,
CERTIFICACION VARCHAR2(50)NULL,
CONSTRAINT PK_COD_PROFESION PRIMARY KEY(COD_PROFESION)
);

CREATE TABLE RETRASO(
COD_CREDITO NUMBER(10) NOT NULL,
MES_VENCIDO VARCHAR2(50) NOT NULL,
MONTO_MORA NUMBER(10) NOT NULL,
CONSTRAINT FK_RETRASO_COD_CREDITO FOREIGN KEY(COD_CREDITO) REFERENCES CREDITOS(COD_CREDITO)
);

ALTER TABLE PERSONA ADD
CONSTRAINT FK_PERSONA_COD_CIUDAD FOREIGN KEY(COD_CIUDAD)REFERENCES
CIUDAD(COD_CIUDAD);


ALTER TABLE EMPLEADO ADD
CONSTRAINT FK_EMPLEADO_COD_CARGO FOREIGN KEY(COD_CARGO) REFERENCES CARGO(COD_CARGO);

ALTER TABLE CLIENTE
ADD (COD_CLIENTE NUMBER(15) NOT NULL);

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_COD_CLIENTE PRIMARY KEY(COD_CLIENTE);

ALTER TABLE USUARIOS
DROP CONSTRAINT FK_USUARIOS_COD_CLIENTE;

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE);

ALTER TABLE EMPLEADO
ADD (COD_PROFESION NUMBER(10));

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_COD_PROFESION FOREIGN KEY(COD_PROFESION) REFERENCES 
PROFESION(COD_PROFESION);

ALTER TABLE USUARIOS_FORMALES
ADD (COD_CARGO NUMBER(10));

ALTER TABLE USUARIOS_FORMALES
ADD CONSTRAINT FK_USUARIOS_FORMALES_COD_CARGO FOREIGN KEY(COD_CARGO) REFERENCES CARGO(COD_CARGO);

INSERT INTO EMPLEADO(NIT,FECHA_INGRESO,HORAS_TRABAJO,DPI,COD_CARGO,COD_PROFESION) 
VALUES(73713333,'10-08-16',8,2169167201401,1,1);

INSERT INTO PROFESION(COD_PROFESION,TITULO,DIPLOMA,CERTIFICACION)
VALUES(1,'Bachiller en Computacion',null,null);

INSERT INTO USUARIOS_FORMALES(NIT,USUARIO,CONTRASEÑA,COD_CARGO)
VALUES(73713333,'JoseLuis','jchepe1623',1);

SELECT P.DPI,P.PNOMBRE,P.PAPELLIDO,E.NIT,U.USUARIO,U.CONTRASEÑA,CA.CARGO
FROM PERSONA P 
FULL JOIN EMPLEADO E ON P.DPI=E.DPI
FULL JOIN USUARIOS_FORMALES U ON U.NIT=E.NIT
FULL JOIN CARGO CA ON CA.COD_CARGO=U.COD_CARGO; 


BEGIN
PRO_PERSONA(2276873456243,'Marta','Lucrecia','Ortiz','Gomez','4ta Calle 9a Avenida','15-08-90',2);
END;

ALTER TABLE CUENTA
DROP CONSTRAINT FK_CUENTA_DPI;

ALTER TABLE CUENTA
ADD CONSTRAINT FK_CUENTA_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE);

COMMIT;

ALTER TABLE CUENTA
DROP  COLUMN DPI; 

ALTER TABLE CUENTA
ADD (COD_CLIENTE NUMBER(10) NOT NULL);

SELECT *FROM CUENTA;

ALTER TABLE DEPOSITOS
ADD CONSTRAINT FK_DEPOSITOS_DPI FOREIGN KEY(DPI) REFERENCES PERSONA(DPI);

ALTER TABLE CREDITOS
DROP CONSTRAINT FK_CREDITOS_DPI;

ALTER TABLE CREDITOS
DROP COLUMN DPI;

ALTER TABLE CREDITOS
ADD (COD_CLIENTE NUMBER(10) NOT NULL);

ALTER TABLE CREDITOS
ADD CONSTRAINT FK_CREDITOS_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE);

COMMIT;


