DESCRIBE USUARIOS_FORMALES;
DESCRIBE PERSONA;
DESCRIBE CIUDAD;
DESCRIBE EMPLEADO;
DESCRIBE CARGO;

INSERT INTO PERSONA VALUES(2169167201401,'Jose','Luis','Azanon','Cabrera','Final Colonia Utatlan','30-10-1992',1);
INSERT INTO CIUDAD VALUES(1,'Santa Cruz','Quiche','Guatemala');
INSERT INTO EMPLEADO VALUES(73713333,'31-07-2016','10',2169167201401,1)
INSERT INTO CARGO VALUES(1,'Cajero','Ventanilla',4000);
INSERT INTO USUARIOS_FORMALES VALUES(73713333,'JoseLuis','D_87h@r_98?74!75H');

SELECT *FROM CIUDAD;
SELECT *FROM PERSONA;
SELECT *FROM CARGO;
SELECT *FROM EMPLEADO;
SELECT *FROM USUARIOS_FORMALES;

CREATE OR REPLACE FUNCTION LOGIN(tex1 in varchar2,text2 in nvarchar2)
IS
RETORNO VARCHAR2;
RETURN;
BEGIN
  SELECT USUARIO,CONTRASEÑA 
  INTO RETORNO
  FROM USUARIOS_FINALES 
  WHERE USUARIO=tex1 AND
  CONTRASEÑA=text2;
  
  IF RETORNO !=EMPTY THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END;







CREATE OR REPLACE FUNCTION LOGIN(tex1 in varchar2,text2 in nvarchar2)
RETURN NUMBER
IS
RETORNO VARCHAR2;
RESULTADO NUMBER;
BEGIN
  SELECT USUARIO,CONTRASEÑA 
  INTO RETORNO
  FROM USUARIOS_FINALES 
  WHERE USUARIO=tex1 AND
  CONTRASEÑA=text2;
  
  IF RETORNO !=EMPTY THEN
    RESULTADO:=1;
    RETURN(RESULTADO);
  ELSE
    RESULTADO:=0;
    RETURN(RESULTADO);
  END IF;
END;


