--PROCEDIMIENTO PERSONA
CREATE OR REPLACE PROCEDURE PRO_PERSONA(E_DPI IN PERSONA.DPI%Type,E_PNOMBRE IN PERSONA.PNOMBRE%Type,E_SNOMBRE IN PERSONA.SNOMBRE%Type,
E_PAPELLIDO IN PERSONA.PAPELLIDO%Type,E_SAPELLIDO IN PERSONA.SAPELLIDO%Type,E_DIRECCION IN PERSONA.DIRECCION%Type,
E_FECHA_NAC IN PERSONA.FECHA_NAC%Type,E_COD_CIUDAD IN PERSONA.COD_CIUDAD%Type)
AS
BEGIN
INSERT INTO PERSONA(DPI,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,DIRECCION,FECHA_NAC,COD_CIUDAD)
VALUES(E_DPI,E_PNOMBRE,E_SNOMBRE,E_PAPELLIDO,E_SAPELLIDO,E_DIRECCION,E_FECHA_NAC,E_COD_CIUDAD);
END;

--PROCEDIMIENTO CIUDAD
CREATE OR REPLACE PROCEDURE PRO_CIUDAD(E_MUNICIPIO IN CIUDAD.MUNICIPIO%Type,
E_DEPARTAMENTO IN CIUDAD.DEPARTAMENTO%Type,E_PAIS IN CIUDAD.PAIS%Type)
AS
BEGIN
INSERT INTO CIUDAD(MUNICIPIO,DEPARTAMENTO,PAIS)
VALUES(E_MUNICIPIO,E_DEPARTAMENTO,E_PAIS);
END;





